### ISSUE TITLE
Supporting Windows via WSL

### ISSUE THREAD

**Issue by JAremko** [purcell/nix-emacs-ci#28]
Since Windows Subsystem for Linux can run Nix and GitHub Actions runners have WSL enabled can it be possible to cross compile  Emacs for Windows and download/install it via WSL?

**Comment by purcell** [comment]
I'm not sure of the value of this. Once Emacs has been compiled via WSL for Windows, isn't it going to behave just like Emacs on Linux?

**Comment by JAremko** [comment]
I mean running Nix stuff in WSL that will install Emacs.exe on Windows system. I don't know how exactly You make those releases but fetching https://ftp.gnu.org/gnu/emacs/windows/ and changing it would help people to have same workflow for testing on Windows/Linux/Mac instead of creating separate one for Windows.

###### I have a feeling that I'm missing something important here :thinking:

**Comment by akirak** [comment]
@JAremko [setup-emacs-windows](https://github.com/jcs090218/setup-emacs-windows) has been recently released, and it's basically an Windows alternative to `setup-emacs`. You probably can run CI on Linux, macOS, and Windows by [defining a matrix](https://github.com/purcell/nix-emacs-ci/actions/runs/222949100/workflow) and run `setup-emacs`/`setup-emacs-windows` conditionally. Is it what you want?

**Comment by JAremko** [comment]
@akirak  sould like it. Thanks :heart:

**Comment by akirak** [comment]
@JAremko If you've resolved this issue, could you close this ticket?

**Comment by JAremko** [comment]
Yeah seems to work pretty well with:

``` yaml
    - name: Install Emacs on UNIX
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
      if: ${{ matrix.os != 'windows-latest' }}

    - name: Install Emacs on Windows
      uses: jcs090218/setup-emacs-windows@master
      with:
        version: ${{ matrix.emacs_version }}
      if: ${{ matrix.os == 'windows-latest' }}

```
